project_id = "qucfdnykdsjmyggunyat"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[fetch.release]]
src = "https://deno.land/std@0.168.0/http/server.ts"