// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvmsosevacmbflsgrcti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2bXNvc2V2YWNtYmZsc2dyY3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjQ4NzEsImV4cCI6MjA3NDc0MDg3MX0.pug3k4mFF_wQhn7077XE8mOBUOY37E1Pk8cRAYCtlIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});