// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qucfdnykdsjmyggunyat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1Y2ZkbnlrZHNqbXlnZ3VueWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNTc4MDIsImV4cCI6MjA1MTkzMzgwMn0.4Stgk-tb_KWR-K8CdsN8fCJB9Bcwm6B7BsL72aY0n90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);